version: 0.2
phases:
  install:
  runtime-versions:
    nodejs: 22
  commands:
    - echo "Installing dependencies..."
    - npm install
    - npm install --save-dev @types/node  # 👈 cài ở root
    - cd cdk && npm install --save-dev @types/node
    - npm install -g aws-cdk@2
  pre_build:
    commands:
      - echo "Compiling TypeScript..."
      - npx tsc
  build:
    commands:
      - echo "Deploying CDK..."
      - cdk deploy --require-approval never --app 'npx ts-node --prefer-ts-exts cdk/bin/app.ts'

